Paup_StudentskaMenza/Controllers/JelaController.cs
using Paup_StudentskaMenza.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Paup_StudentskaMenza.Misc;
using System.Net;
using Paup_StudentskaMenza.Reports;

namespace Paup_StudentskaMenza.Controllers
{
    public class JelaController : BaseController
    {
        // GET: Meni
        private BazaDbContext bazaPodataka = new BazaDbContext();


        // GET: Studenti
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Title = "Popis Jela";
            ViewBag.Menza = "Studentska menza";
           
            return View(bazaPodataka.PopisJela.ToList());
        }

        [AllowAnonymous]

        public ActionResult Azuriraj(int? id)
        {

            Jela jelo;
            
            if (!id.HasValue)
            {
                jelo = new Jela();
                ViewBag.Title = "Kreiranje jela";
                ViewBag.Novi = true;
            }
            //ako id postoji onda provjeravamo ako taj student postoji u bazi podataka
            else
            {
                jelo = bazaPodataka.PopisJela.FirstOrDefault(x => x.Id == id);

                //ako u listi nema studenta sa traženim Id-em onda je objekt student null
                if (jelo == null)
                {
                    //return new HttpStatusCodeResult(HttpStatusCode.NotFound);
                    //Ili skraćeno
                    return HttpNotFound();
                }

                ViewBag.Title = "Ažuriranje jela";
                ViewBag.Novi = false;

            }
           
            var ovlast = bazaPodataka.PopisOvlasti.OrderBy(x => x.Naziv).ToList();
            ViewBag.Ovlast = ovlast;
            //var status = bazaPodataka.PopisStatusa.OrderBy(x => x.id).ToList();
            //ViewBag.Status = status;

            return View(jelo);
        }
        [AllowAnonymous]
        public ActionResult IspisJela(string naziv,  string cijena,  string sort, int? page)
        {
            //System.Threading.Thread.Sleep(200); //simulacija duže obrade zahtjeva

            ViewBag.Sortiranje = sort;
            ViewBag.NazivSort = String.IsNullOrEmpty(sort) ? "naziv_desc" : "";
            ViewBag.CijenaSort = sort == "cijena" ? "smjer_desc" : "smjer";
            ViewBag.Cijena = cijena;
            ViewBag.Naziv = naziv;
            
            

            var jela = bazaPodataka.PopisJela.ToList();

            //filtriranje
            if (!String.IsNullOrWhiteSpace(naziv))
            {
                jela = jela.Where(x => x.Naziv.ToUpper().Contains(naziv.ToUpper())).ToList();
            }

            if (!String.IsNullOrWhiteSpace(cijena))
            {
                jela = jela.Where(x => x.Cijena.ToString() == cijena).ToList();
            }

           
            switch (sort)
            {
                case "naziv_desc":
                    jela = jela.OrderByDescending(s => s.Naziv).ToList();
                    break;
                case "smjer":
                    jela = jela.OrderBy(s => s.Cijena).ToList();
                    break;
                case "smjer_desc":
                    jela = jela.OrderByDescending(s => s.Cijena).ToList();
                    break;
                default:
                    jela = jela.OrderBy(s => s.Naziv).ToList();
                    break;
            }

            JelaReport jelaReport = new JelaReport();
            jelaReport.ListaJela(jela);

            return File(jelaReport.Podaci, System.Net.Mime.MediaTypeNames.Application.Pdf,
                "PopisJela.pdf");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Azuriraj(Jela jelo)
        {
            /*LogiraniKorisnik k = User as LogiraniKorisnik;
            if (k != null)
            {
                ViewBag.Logirani = k.KorisnickoIme;
            }*/

            if (ModelState.IsValid)
            {
                //ako model ima vrijednost parametra Id različito od 0 tada znamo da korisnik ažurira podatke o studentu
                if (jelo.Id != 0)
                {
                    bazaPodataka.Entry(jelo).State = System.Data.Entity.EntityState.Modified;
                }
                //ako model ima vrijednost parametra Id jednak 0 tada se radi o dodavanju novog studenta
                else
                {
                    bazaPodataka.PopisJela.Add(jelo);
                }
                bazaPodataka.SaveChanges();
                return RedirectToAction("Index");
            }

            if (jelo.Id == 0)
            {
                ViewBag.Title = "Kreiranje jela";
                ViewBag.Novi = true;
            }
            else
            {
                ViewBag.Title = "Ažuriranje jela";
                ViewBag.Novi = false;
            }
            return View(jelo);
        }
      

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Popis");
            }

            //dohvaćamo studenta iz baze podataka na temelju id
            Jela jelo = bazaPodataka.PopisJela.FirstOrDefault(x => x.Id == id);

            //ako ne postoji student s tim id-em vraćamo HTTP status Not found
            if (jelo == null)
            {
                return HttpNotFound();
            }

            ViewBag.Title = "Potvrda brisanja studenta";
            return View(jelo);
        }

        // POST: Smjerovi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jela jelo = bazaPodataka.PopisJela.Find(id);
            bazaPodataka.PopisJela.Remove(jelo);
            bazaPodataka.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                bazaPodataka.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

Paup_StudentskaMenza/Controllers/KorisniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Paup_StudentskaMenza.Models;
using Paup_StudentskaMenza.Misc;
using System.Web.Script.Serialization;
using Paup_StudentskaMenza.Controllers;


namespace Paup_StudentskaMenza.Controllers
{
    public class KorisniciController : BaseController
    {
        BazaDbContext bazaPodataka = new BazaDbContext();
        // GET: Korisnici
        public ActionResult Index()
        {
            var listaKorisnika = bazaPodataka.PopisKorisnika.OrderBy(x => x.SifraOvlasti).ThenBy(x => x.Prezime).ToList();
            return View(listaKorisnika);
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Prijava(string returnUrl)
        {
            KorisnikPrijava model = new KorisnikPrijava();
            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Prijava(KorisnikPrijava model,string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var korisnikBaza = bazaPodataka.PopisKorisnika.FirstOrDefault(x => x.KorisnickoIme == model.KorisnickoIme);
                if(korisnikBaza !=null)
                {
                    var passwordOK = korisnikBaza.Lozinka == Misc.PasswordHelper.IzracunajHash(model.Lozinka);
                    if (passwordOK)
                    {
                        LogiraniKorisnik prijavljeniKorisnik = new LogiraniKorisnik(korisnikBaza);
                        LogiraniKorisnikSerializeModel serializeModel = new LogiraniKorisnikSerializeModel();
                        serializeModel.CopyFromUser(prijavljeniKorisnik);
                        JavaScriptSerializer serializer = new JavaScriptSerializer();
                        string korisnickiPodaci = serializer.Serialize(serializeModel);

                        FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket(
                            1,
                            prijavljeniKorisnik.Identity.Name,
                            DateTime.Now,
                            DateTime.Now.AddDays(1),
                            false,
                            korisnickiPodaci);

                        string ticketEncrypted = FormsAuthentication.Encrypt(authTicket);
                        HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, ticketEncrypted);
                        Response.Cookies.Add(cookie);

                        if(!String.IsNullOrEmpty(returnUrl)&&Url.IsLocalUrl(returnUrl))
                        {
                            return Redirect(returnUrl);

                        }
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            ModelState.AddModelError("", "Neispravno korisnicko ime ili lozinka");
            return View(model);
        }
        public ActionResult Odjava()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Registracija()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Registracija(Korisnik model)
        {
            if (!String.IsNullOrWhiteSpace(model.KorisnickoIme))
            {
                //metoda Any vraća ako postoji (true/false) barem jedan zapis koji zadovoljava uvjete pretrage
                var korImeZauzeto = bazaPodataka.PopisKorisnika.Any(x => x.KorisnickoIme == model.KorisnickoIme);
                if (korImeZauzeto)
                {
                    ModelState.AddModelError("KorisnickoIme", "Korisničko ime je već zauzeto");
                }
            }
            if (!String.IsNullOrWhiteSpace(model.Email))
            {
                var emailZauzet = bazaPodataka.PopisKorisnika.Any(x => x.Email == model.Email);
                if (emailZauzet)
                {
                    ModelState.AddModelError("Email", "Email je već zauzet");
                }
            }

            if (ModelState.IsValid)
            {
                model.Lozinka = Misc.PasswordHelper.IzracunajHash(model.LozinkaUnos);
                model.SifraOvlasti = "MO";

                bazaPodataka.PopisKorisnika.Add(model);
                bazaPodataka.SaveChanges();

                return View("RegistracijaOk");
            }

            var ovlasti = bazaPodataka.PopisOvlasti.OrderBy(x => x.Naziv).ToList();
            ViewBag.Ovlasti = ovlasti;

            return View(model);
        }
    }
}
 

Paup_StudentskaMenza/Controllers/MeniController.cs
using Paup_StudentskaMenza.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Paup_StudentskaMenza.Misc;


namespace Paup_StudentskaMenza.Controllers
{
    public class MeniController : BaseController
    {
        // GET: Meni
        BazaDbContext bazaPodataka = new BazaDbContext();

     
       
        // GET: Studenti
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Title = "Početna stranica";
            ViewBag.Menza = "Studentska menza";
            
            
          
            return View();
        }

        [AllowAnonymous]
        public ActionResult Popis()
        {
            var listaJela = bazaPodataka.PopisJela.OrderBy(x => x.Naziv).ToList();
            ViewBag.Jela = listaJela;
            return View();        
        }

         [AllowAnonymous]
        public ActionResult PopisPartial(string naziv)
        {
            //System.Threading.Thread.Sleep(200); //simulacija duže obrade zahtjeva

            ViewBag.Naziv = naziv;
            var jela = bazaPodataka.PopisMeni.ToList();

            //filtriranje
            if (!String.IsNullOrWhiteSpace(naziv))
            {
                jela = jela.Where(x => x.NazivJelo.Naziv.ToUpper().Contains(naziv.ToUpper())).ToList();
            }
           

            return PartialView("_PartialPopis", jela);
        }

         public ActionResult Dodaj()
         {
            Meni jelo;
            jelo = new Meni();
            // JelaRepo listaJela = new JelaRepo(); 
            // var jela = new Tuple<IEnumerable<SelectListItem>>(listaJela.SvaJela());
            var listaJela = bazaPodataka.PopisJela.OrderBy(x => x.Naziv).ToList();
            
            ViewBag.Jela = listaJela;


            return View(jelo);
         }

        
         [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Dodaj(Meni j)
         {
             LogiraniKorisnik k = User as LogiraniKorisnik;
             if (k != null)
             {
                 ViewBag.Logirani = k.KorisnickoIme;
             }

            bazaPodataka.PopisMeni.Add(j);

            bazaPodataka.SaveChanges();

            return RedirectToAction("Popis");
         }

        [HttpGet]
        public JsonResult dohvatiCijenu(int jeloId)
        {
            decimal jeloCijena = bazaPodataka.PopisJela.SingleOrDefault(model => model.Id == jeloId).Cijena;
            return Json(jeloCijena, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Brisi(int? id)
        {
            //ako id nije defiran preusmjeravamo korisnika na popis studenata
            if (id == null)
            {
                return RedirectToAction("Popis");
            }

            //dohvaćamo studenta iz baze podataka na temelju id
            Meni m = bazaPodataka.PopisMeni.FirstOrDefault(x => x.Idmeni == id);

            //ako ne postoji student s tim id-em vraćamo HTTP status Not found
            if (m == null)
            {
                return HttpNotFound();
            }

            ViewBag.Title = "Potvrda brisanja jela s menija";
            return View(m);
        }

        //Metoda za brisanje studenta
        //Poziva je metoda za potvrdu brisanja
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Brisi(int id)
        {
            Meni m = bazaPodataka.PopisMeni.FirstOrDefault(x => x.Idmeni == id);
            if (m == null)
            {
                return HttpNotFound();
            }

            bazaPodataka.PopisMeni.Remove(m);
            bazaPodataka.SaveChanges();

            //Ovdje smo definirali kao parametar naziv viewa koji metoda vraća
            //Pošto GET metoda Brisi vraća view Brisi ovdje putem parametra definiramo koji view vraća ova metoda
            //U tom viewu će biti prikazan status brisanja
            return View("BrisiStatus");
        }




    }
}

Paup_StudentskaMenza/Controllers/SopingKosaricaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Paup_StudentskaMenza.Models;
using Paup_StudentskaMenza.ViewModels;

namespace Paup_StudentskaMenza.Controllers
{
    public class SopingKosaricaController : BaseController
    {
        // GET: SopingKosarica
        BazaDbContext storeDB = new BazaDbContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = SopingKosarica.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new SopingKosaricaViewModel
            {
                CartItems = cart.GetCartItems(),
                KosaricaUkupno = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var dodanoJelo = storeDB.PopisJela
                .Single(jelo => jelo.Id == id);

            // Add it to the shopping cart
            var cart = SopingKosarica.GetCart(this.HttpContext);

            cart.AddToCart(dodanoJelo);

            // Go back to the main store page for more shopping
            return RedirectToAction("Popis","Meni");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = SopingKosarica.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string nazivJela = storeDB.Kosarice
                .Single(item => item.StavkaId == id).Jelo.Naziv;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new UkloniKosaricuViewModel
            {
                Message = Server.HtmlEncode(nazivJela) +
                    " je uklonjeno iz vaše košarice",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = SopingKosarica.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Paup_StudentskaMenza/Views/Meni/Brisi.cshtml
@model Paup_StudentskaMenza.Models.Meni

@{
    ViewBag.Title = "Briši";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<strong>Jeste li sigurni da želita izbrisati jelo @Model.NazivJelo.Naziv iz dana @Model.dan ?</strong>

<br />
<br />

@using (Html.BeginForm("Brisi", "Meni"))
{
    @Html.AntiForgeryToken();

    <button type="submit" class="btn btn-danger">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Izbriši
    </button>

    <br />
    <br />

    @Html.ActionLink("Odustani", "Popis")
}

Paup_StudentskaMenza/Views/Meni/BrisiStatus.cshtml
@{
    ViewBag.Title = "Status brisanja jela s menija";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="alert alert-success" role="alert">Podaci uspješno izbrisani!</div>

@Html.ActionLink("Povratak na popis", "Popis")

Paup_StudentskaMenza/Views/Meni/Dodaj.cshtml
@using Paup_StudentskaMenza.Models

@model Meni


@{
    ViewBag.Title = "Dodaj";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<h3>Dodaj jelo</h3>

@using (Html.BeginForm("Dodaj", "Meni", FormMethod.Post, new { @class = "form-horizontal", role = "form"})) 
{
    @*
        Html.AntiForgeryToken() - mehanizam koji nas štiti od cross site request forgery
        (poziva HTTP POST metode izvan naše aplikacije)
    *@
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "Ispravite podatke!");

    <div class="row">
        <div class="form-group">
            @Html.LabelFor(model => model.idjelo, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.DropDownListFor(model => model.idjelo,
             new SelectList(ViewBag.Jela, "Id", "Naziv", ""), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idjelo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.dan, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.EnumDropDownListFor(model => model.dan, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.dan, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="false"></span> Spremi
                </button>
            </div>
        </div>
    </div>

}
@Html.ActionLink("Povratak bez spremanja", "Popis", "Meni")

Paup_StudentskaMenza/Views/Meni/Popis.cshtml
@using Paup_StudentskaMenza.Misc;


@{
    ViewBag.Title = "Meni";
    Layout = "~/Views/Shared/_Layout.cshtml";
    AjaxOptions ajaxOpt = new AjaxOptions()
    {
        UpdateTargetId = "popisMenija",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET",
        OnBegin = "LoadingRow"
    };
}



<h2>Ovotjedni meni</h2>





@if (User.Identity.IsAuthenticated &&
                         (User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administrator))
{
    <a href="@Url.Action("Dodaj", "Meni")" class="btn btn-success">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj jelo
    </a>
}

<br />
<br />




@{
    Html.RenderAction("PopisPartial", new { naziv = "" });
}

@section Scripts{
    <script type="text/javascript">
        function LoadingRow() {
            $("#tableJela tbody").empty();

            $("#tableJela tbody").append('<tr><td colspan="7" style="text-align: center">Pretraga u tijeku...</td></tr>');

          
        }
    </script>
    }

Paup_StudentskaMenza/Views/Meni/_PartialPopis.cshtml
@using Paup_StudentskaMenza.Models
@using Paup_StudentskaMenza.Misc;
@model List<Meni>
@{
    AjaxOptions ajaxOpt = new AjaxOptions()
    {
        UpdateTargetId = "popisMenija",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET",
        OnBegin = "LoadingRow"
    };

}

<div id="popisMenija">
    @for (int i = 0; i < 7; i++)
    {
        if (i == 0)
        {
            <h3>Danas je @DateTime.Now.AddDays(i).Date.ToString("dddd"), @DateTime.Now.AddDays(i).Date.ToShortDateString()</h3>
        }
        else
        {
            <h3> @DateTime.Now.AddDays(i).Date.ToString("dddd").ToUpper(), @DateTime.Now.AddDays(i).Date.ToShortDateString()</h3>
        }

        <table id="tableJela" class="table table-striped" >

            <thead style="color:palevioletred">
                <tr>
                    <th hidden>Id</th>

                    <th scope="col">
                        <strong>Naziv</strong>
                    </th>
                    <th >Opis</th>
                    <th>Cijena</th>
                    <th>Vege</th>
                    @if (i == 0 && User.Identity.IsAuthenticated)
                    {
                        <th>Akcije</th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    foreach (var meni in Model)
                    {
                        if (meni.dan.ToString().ToUpper() == DateTime.Now.AddDays(i).Date.ToString("dddd").ToUpper())
                        {
                <tr>
                    <td hidden>@meni.Idmeni</td>
                    <td>@(meni.NazivJelo?.Naziv)</td>
                    <td>@(meni.NazivJelo?.Opis)</td>
                    <td>@(meni.NazivJelo?.Cijena)</td>
                    @if (meni.NazivJelo.Vege == true)
                    {
                        <td>Da</td>
                    }
                    else
                    {
                        <td>Ne</td>
                    }

                    @if (i == 0)
                    {
                <td>
                    @if (User.Identity.IsAuthenticated)
                    {

                        @Html.ActionLink("Dodaj u košaricu", "AddToCart", "SopingKosarica", new { id = meni.idjelo }, new { @class = "btn btn-success btn-sm " })
                    }
                    else
                    {
                        @Html.ActionLink("Dodaj u košaricu", "Prijava", "Korisnici", new { id = meni.idjelo }, new { @class = "btn btn-success btn-sm " })
                    }



                    @if (User.Identity.IsAuthenticated &&
                        ((User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administrator)))
                    {
                        @Html.ActionLink("Ažuriraj", "Azuriraj", "Jela", new { id = meni.idjelo }, new { @class = "btn btn-info btn-sm " })
                        @Html.ActionLink("Izbriši", "Brisi", new { id = meni.Idmeni }, new { @class = "btn btn-danger btn-sm" })



                    }
                </td>
                    }


                    else
                    {
                        if (User.Identity.IsAuthenticated &&
                        ((User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administrator)))
                        {


                        <td>
                            @Html.ActionLink("Ažuriraj", "Azuriraj", "Jela", new { id = meni.idjelo }, new { @class = "btn btn-info btn-sm" })

                            @Html.ActionLink("Izbriši", "Brisi", new { id = meni.Idmeni }, new { @class = "btn btn-danger btn-sm" })
                        </td>

                        }

                    }
                    </tr>
                        }
                    }
                }

                else
                {
                    <tr>
                        <td colspan="7" style="text-align:center;"> Nema rezultata pretrage</td>


                    </tr>
                }


            </tbody>
        </table>
    }

   
</div>