Paup_StudentskaMenza/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Paup_StudentskaMenza.Misc;
using Paup_StudentskaMenza.Models;

namespace Paup_StudentskaMenza.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            LogiraniKorisnik logkor = User as LogiraniKorisnik;
            if(logkor !=null)
            {
                ViewBag.Logirani = logkor.KorisnickoIme;

            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [HttpPost]
        public ActionResult Contact(Mail e)
        {
            LogiraniKorisnik k = User as LogiraniKorisnik;
            using (MailMessage mm = new MailMessage(k.Email, "testnimail555@gmail.com"))
            {
                mm.Subject = "Zahtjev za jelo";
                mm.Body = e.Poruka;
                /*if (model.Attachment.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(model.Attachment.FileName);
                    mm.Attachments.Add(new Attachment(model.Attachment.InputStream, fileName));
                }*/
                mm.IsBodyHtml = false;
                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential(k.Email, "loznika123");
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mm);
                    ViewBag.Message = "Poruka poslana.";
                }
            }
           
            return View();
        }

      
    }
}

Paup_StudentskaMenza/Controllers/MeniController.cs
using Paup_StudentskaMenza.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Paup_StudentskaMenza.Misc;


namespace Paup_StudentskaMenza.Controllers
{
    public class MeniController : BaseController
    {
        // GET: Meni
        BazaDbContext bazaPodataka = new BazaDbContext();

     
       
        // GET: Studenti
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Title = "Početna stranica";
            ViewBag.Menza = "Studentska menza";
            
            
          
            return View();
        }

        [AllowAnonymous]
        public ActionResult Popis()
        {
            var listaJela = bazaPodataka.PopisJela.OrderBy(x => x.Naziv).ToList();
            ViewBag.Jela = listaJela;
            return View();        
        }

         [AllowAnonymous]
        public ActionResult PopisPartial(string naziv)
        {
            //System.Threading.Thread.Sleep(200); //simulacija duže obrade zahtjeva

            ViewBag.Naziv = naziv;
            var jela = bazaPodataka.PopisMeni.ToList();

            //filtriranje
            if (!String.IsNullOrWhiteSpace(naziv))
            {
                jela = jela.Where(x => x.NazivJelo.Naziv.ToUpper().Contains(naziv.ToUpper())).ToList();
            }
           

            return PartialView("_PartialPopis", jela);
        }

         public ActionResult Dodaj()
         {
            Meni jelo;
            jelo = new Meni();
            // JelaRepo listaJela = new JelaRepo(); 
            // var jela = new Tuple<IEnumerable<SelectListItem>>(listaJela.SvaJela());
            var listaJela = bazaPodataka.PopisJela.OrderBy(x => x.Naziv).ToList();
            
            ViewBag.Jela = listaJela;


            return View(jelo);
         }

        
         [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Dodaj(Meni j)
         {
             LogiraniKorisnik k = User as LogiraniKorisnik;
             if (k != null)
             {
                 ViewBag.Logirani = k.KorisnickoIme;
             }

            bazaPodataka.PopisMeni.Add(j);

            bazaPodataka.SaveChanges();

            return RedirectToAction("Popis");
         }

        [HttpGet]
        public JsonResult dohvatiCijenu(int jeloId)
        {
            decimal jeloCijena = bazaPodataka.PopisJela.SingleOrDefault(model => model.Id == jeloId).Cijena;
            return Json(jeloCijena, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Brisi(int? id)
        {
            //ako id nije defiran preusmjeravamo korisnika na popis studenata
            if (id == null)
            {
                return RedirectToAction("Popis");
            }

            //dohvaćamo studenta iz baze podataka na temelju id
            Meni m = bazaPodataka.PopisMeni.FirstOrDefault(x => x.Idmeni == id);

            //ako ne postoji student s tim id-em vraćamo HTTP status Not found
            if (m == null)
            {
                return HttpNotFound();
            }

            ViewBag.Title = "Potvrda brisanja jela s menija";
            return View(m);
        }

        //Metoda za brisanje studenta
        //Poziva je metoda za potvrdu brisanja
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Brisi(int id)
        {
            Meni m = bazaPodataka.PopisMeni.FirstOrDefault(x => x.Idmeni == id);
            if (m == null)
            {
                return HttpNotFound();
            }

            bazaPodataka.PopisMeni.Remove(m);
            bazaPodataka.SaveChanges();

            //Ovdje smo definirali kao parametar naziv viewa koji metoda vraća
            //Pošto GET metoda Brisi vraća view Brisi ovdje putem parametra definiramo koji view vraća ova metoda
            //U tom viewu će biti prikazan status brisanja
            return View("BrisiStatus");
        }




    }
}

Paup_StudentskaMenza/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Paup_StudentskaMenza/Views/Home/Contact.cshtml
@using Paup_StudentskaMenza.Models
@model Mail
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Contact", "Home", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.ValidationSummary()
<div class="row">
    <div class="form-group">
        <label for="textArea" class="col-lg-2 control-label">Novo jelo</label>
        <div class="col-lg-2">
            @Html.TextAreaFor(model => model.Poruka, new { @placeholder = "Poruka *" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button name="submit" type="submit" class="btn btn-primary">Pošalji</button>
        </div>
    </div>
</div>
<span style="color:green">@ViewBag.Message</span>
        }

Paup_StudentskaMenza/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Menza";
}

<div class=" jumbotron text-center" style="background-image: url('/Content/Slike/caffeteria.png'); width:inherit;">
           
        <h1 style="color:white; border:solid 2px;padding:.2em; background-color:rgba(0, 0, 0, 0.5);">Pogledaj ovotjedni meni</h1>
        <button class="btn btn-primary" onclick="location.href='@Url.Action("Popis", "Meni")';">Saznaj više &raquo;</button>
    </div>


<div class="row" >
    <div class="col-md-4 text-warning" style="background-image: url('/Content/Slike/jelo.png'); width:400px; color:white; border:solid 2px;padding:.5em; background-color:rgba(0, 0, 0, 0.5); border-radius:10px">
        <h2>Predloži jelo</h2>
        <blockquote>
            <p>
                Javi nam ako želiš vidjeti novo jelo na meniju.
            </p>
        </blockquote>
        <button class="btn btn-success" style="color: white" onclick="location.href='@Url.Action("Contact", "Home")';">Kontakt &raquo;</button>
    </div>
  
</div>